CREATE TABLE coach
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255) NOT NULL,
    date_of_birth date         NOT NULL,
    nationality   VARCHAR(255) NOT NULL,
    CONSTRAINT pk_coach PRIMARY KEY (id)
);

CREATE TABLE competition
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR(255),
    code      VARCHAR(255),
    area_name VARCHAR(255),
    CONSTRAINT pk_competition PRIMARY KEY (id)
);

CREATE TABLE player
(
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name          VARCHAR(255) NOT NULL,
    position      VARCHAR(255) NOT NULL,
    date_of_birth date         NOT NULL,
    nationality   VARCHAR(255) NOT NULL,
    team_id       BIGINT,
    CONSTRAINT pk_player PRIMARY KEY (id)
);

CREATE TABLE team
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    tla        VARCHAR(255),
    short_name VARCHAR(255),
    area_name  VARCHAR(255),
    address    VARCHAR(255),
    coach_id   BIGINT,
    CONSTRAINT pk_team PRIMARY KEY (id)
);

CREATE TABLE team_competitions
(
    competitions_id BIGINT NOT NULL,
    team_id         BIGINT NOT NULL,
    CONSTRAINT pk_team_competitions PRIMARY KEY (competitions_id, team_id)
);

ALTER TABLE competition
    ADD CONSTRAINT uc_competition_code UNIQUE (code);

ALTER TABLE team
    ADD CONSTRAINT uc_team_coach UNIQUE (coach_id);

ALTER TABLE team
    ADD CONSTRAINT uc_team_name UNIQUE (name);

ALTER TABLE player
    ADD CONSTRAINT FK_PLAYER_ON_TEAM FOREIGN KEY (team_id) REFERENCES team (id);

ALTER TABLE team
    ADD CONSTRAINT FK_TEAM_ON_COACH FOREIGN KEY (coach_id) REFERENCES coach (id);

ALTER TABLE team_competitions
    ADD CONSTRAINT fk_teacom_on_competition FOREIGN KEY (competitions_id) REFERENCES competition (id);

ALTER TABLE team_competitions
    ADD CONSTRAINT fk_teacom_on_team FOREIGN KEY (team_id) REFERENCES team (id);